#!/usr/bin/env php
# curl https://raw.githubusercontent.com/jtsternberg/Dot-Files/master/misc/bootstrap | php
echo $OSTYPE
<?php
$os_type = `echo \$OSTYPE`;
echo '$OSTYPE:' . $os_type . "\n";

echo "Clone Dot-Files\n";
echo `git clone --recursive https://github.com/jtsternberg/Dot-Files.git ~/.dotfiles`;

if ( false !== stripos( $os_type, 'linux' ) ) {

	echo "Get OS packages\n";
	echo `sudo apt-get -y install zsh tree tig wget`;

	echo "Symlink dotfiles\n";
	echo `cd ~/.dotfiles && chmod +x symdotfiles && bash symdotfiles`;

	echo "install oh-my-zsh\n";
	echo `curl -L http://install.ohmyz.sh | sh`;

	echo "switch shell\n";
	echo `chsh -s $(which zsh)`;

}
