#!/usr/bin/env php
# curl https://raw.githubusercontent.com/jtsternberg/Dot-Files/master/misc/bootstrap | sudo php -- $OSTYPE

<?php
$os_type = isset( $argv[1] ) ? $argv[1] . "\n" : `echo \$OSTYPE`;
echo "\n" . '>> $OSTYPE: ' . $os_type . "\n";

echo "\n>> Clone Dot-Files\n";
echo `git clone --recursive https://github.com/jtsternberg/Dot-Files.git ~/.dotfiles`;

if ( false !== stripos( $os_type, 'linux' ) ) {

	echo "\n>> Get OS packages\n\n";
	echo `sudo apt-get -y install zsh tree tig wget`;

	echo "\n>> install oh-my-zsh\n\n";
	echo `curl -L http://install.ohmyz.sh | sh && rm -rf ~/.zshrc`;

	echo "\n>> Symlink dotfiles\n\n";
	echo `cd ~/.dotfiles && chmod +x symdotfiles && bash symdotfiles`;

	echo "\n>> switch shell\n\n";
	echo "\n>> Don't forget to change your shell! `chsh -s $(which zsh)`\n\n";
	echo `chsh -s $(which zsh)`;
}
