#!/usr/bin/env php
# curl https://raw.githubusercontent.com/jtsternberg/Dot-Files/master/misc/bootstrap | sudo php -- $OSTYPE

<?php
$os_type = isset( $argv[1] ) ? $argv[1] . "\n" : `echo \$OSTYPE`;
do_notice( trim( '$OSTYPE: ' . $os_type ) );

do_notice( 'Clone Dot-Files' );
echo `git clone --recursive https://github.com/jtsternberg/Dot-Files.git ~/.dotfiles`;

if ( false !== stripos( $os_type, 'linux' ) ) {

	do_notice( 'Get OS packages' );
	echo `sudo apt-get -y install zsh tree tig wget`;

	do_notice( 'Install oh-my-zsh' );
	echo `curl -L http://install.ohmyz.sh | sh`;

	do_notice( 'Removing Oh My Zsh .zshrc (to be replaced with ours)', "\n", "\n" );
	echo `rm -rf ~/.zshrc`;

	do_notice( 'Symlink dotfiles' );
	echo `cd ~/.dotfiles && chmod +x symdotfiles && bash symdotfiles`;

	# echo "\n>> Switch shell\n\n";
	echo `chsh -s $(which zsh)`;

	do_notice( "Don&rsquo;t forget to change your shell! `chsh -s $(which zsh)`" );

}

function do_notice( $text, $before = "\n", $after = "\n\n" ) {
	$text = html_entity_decode( $text );
	echo $before;
	echo `echo '>>>' && echo '\033[0;34m>> $text\033[0m' && echo '>>>'`;
	echo $after;
}
