#!/usr/bin/env bash

# curl https://raw.githubusercontent.com/jtsternberg/Dot-Files/master/misc/bootstrap-linux | bash

git clone --recursive https://github.com/jtsternberg/Dot-Files.git ~/.dotfiles
sudo apt-get -y install zsh tree tig wget

curl -L http://install.ohmyz.sh | sh
rm -rf ~/.zshrc
cd ~/.dotfiles && chmod +x symdotfiles && bash symdotfiles

chsh -s $(which zsh)

